# Site settings
title: Code Bytes
header-img: img/home-bg.png
email: ehughes@knights.ucf.edu
copyright_name: FreeBreadsticks
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on code, design, and development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FreeBreadsticks
learn_profile: FreeBreadsticks
email_username: ehughes@knights.ucf.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
